#define IPC_CL_PROCESS_ID_NAME "main-process-id"
#define IPC_CL_LOG_DIRECTORY_NAME "log-directory"

#define IPC_LOG_EVENT "log-event"

#define IPC_JS_WINDOW_OBJECT_NAME "window"
#define IPC_JS_CONTEXT_CREATED "js-context-created"
#define IPC_JS_FUNCTION_CALL_EVENT "1"
#define IPC_JS_FUNCION_ADD_EVENT "2"
#define IPC_JS_FUNCTION_REMOVE_EVENT "3"
#define IPC_JS_EVENT_FUNCTION_ADD_NAME "IPC_JS_EVENT_FUNCTION_ADD_NAME"
#define IPC_JS_EVENT_FUNCTION_CALL_EVENT "5"
